version: '3.4'

services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "26298:80"

  frontend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:443;http://*:80
      - ASPNETCORE_HTTPS_PORT=44376
    ports:
      - "64364:80"
      - "44376:443"
    volumes:
      - $APPDATA/Microsoft/UserSecrets/aspnet-FrontEnd-FC7A9125-D2E6-49EC-B0A7-0A2262EC4AD2:/root/.microsoft/usersecrets/aspnet-FrontEnd-FC7A9125-D2E6-49EC-B0A7-0A2262EC4AD2
      - $APPDATA/ASP.NET/Https:/root/.aspnet/https/